name = "MeasureRight"
client_id = "4fb82d0df17fa7c58057ed8604f4fe0b"
application_url = "https://measureright-production-4bef.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_products,read_themes,write_draft_orders,write_products,write_themes"

[auth]
redirect_urls = [ "https://measureright-production-4bef.up.railway.app/api/auth/callback" ]

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/api/webhooks/orders-paid"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://measureright-production-4bef.up.railway.app/api/webhooks"

[app_proxy]
url = "https://measureright-production-4bef.up.railway.app/proxy"
subpath = "measureright"
prefix = "apps"

[pos]
embedded = false
